### ISSUE TITLE
ST_SubDivide (Snowflake) fails even on documentation example

### ISSUE THREAD

**Issue by andreypanchenko** [apache/sedona#1288] opened 2024-03-23 17:46 UTC
## Expected behavior

`SELECT ST_SubDivide(ST_GeomFromText('POLYGON((35 10, 45 45, 15 40, 10 20, 35 10), (20 30, 35 35, 30 20, 20 30))'), 5) `

==============================================================================================
MULTILINESTRING ((0 0, 5 5), (5 5, 10 10), (10 10, 21 21), (21 21, 60 60), (60 60, 85 85), (85 85, 100 100), (100 100, 120 120))

[doc_example](https://sedona.apache.org/1.5.1/api/snowflake/vector-data/Function/#st_subdivide)

## Actual behavior
![image](https://github.com/apache/sedona/assets/26185177/0788bc77-5ef9-458f-a7a8-bb86dd399036)

## Steps to reproduce the problem
https://sedona.apache.org/1.5.1/setup/snowflake/install/
sedona-snowflake-1.5.1.jar: [Sedona's Maven Central repository](https://central.sonatype.com/artifact/org.apache.sedona/sedona-snowflake/versions)
geotools-wrapper-1.5.1-28.2.jar: [GeoTools-wrapper's Maven Central repository](https://central.sonatype.com/artifact/org.datasyslab/geotools-wrapper/versions)

`java -jar sedona-snowflake-1.5.1.jar --geotools-version 1.5.1-28.2 > sedona-snowflake.sql`
## Settings

Sedona version = 1.5.1

Environment = Snowflake
[SEDONA-519](https://issues.apache.org/jira/projects/SEDONA/issues/SEDONA-519?filter=allopenissues)

**Comment by jiayuasu** [comment] 2024-03-24 07:50
@andreypanchenko Thanks for reporting this. Do you have other Java-based UDF or jars used in the same warehouse?

**Comment by andreypanchenko** [comment] 2024-03-24 09:21
@jiayuasu 
Hi. This exactly from sedona schema as mentioned in guide. Any othe java UDfs at all.

**Comment by andreypanchenko** [comment] 2024-03-24 09:52
I really keen to use this feature. What additional info I can provide to u?

**Comment by andreypanchenko** [comment] 2024-03-24 11:29
@jiayuasu btw the same issue when I tried to call this function from snowflake store application snowsedona

**Comment by Kontinuation** [comment] 2024-03-24 12:36
This is caused by dependency changes of `geotools-wrapper-1.5.1-28.2.jar`, Apache commons-lang3 was removed from the geotools-wrapper jar, and it is required by ST_SubDivide function, thus caused this problem. I am already working on a fix for this (see https://github.com/apache/sedona/pull/1290 and https://github.com/wherobots/sedona-snowflake-tester/pull/20).

You can also try replacing `geotools-wrapper-1.5.1-28.2.jar` with `geotools-wrapper-1.5.0-28.2.jar` to workaround this issue.

**Comment by jiayuasu** [comment] 2024-03-24 15:20
@andreypanchenko You can download the `geotools-wrapper-1.5.0-28.2.jar` [here](https://repo1.maven.org/maven2/org/datasyslab/geotools-wrapper/1.5.0-28.2/geotools-wrapper-1.5.0-28.2.jar) and replace the current `geotools-wrapper` jar in your Snowflake stage.

**Comment by jiayuasu** [comment] 2024-03-24 19:12
@andreypanchenko The SedonaSnow app on Snowflake marketplace is now pending approval. Once that is done, we will release it to your account automatically. Will keep you posted.

**Comment by andreypanchenko** [comment] 2024-03-25 08:11
> @andreypanchenko You can download the `geotools-wrapper-1.5.0-28.2.jar` [here](https://repo1.maven.org/maven2/org/datasyslab/geotools-wrapper/1.5.0-28.2/geotools-wrapper-1.5.0-28.2.jar) and replace the current `geotools-wrapper` jar in your Snowflake stage.

@jiayuasu 
It's working, thank you!

**Closed** 2024-03-26 03:46 UTC
