### ISSUE TITLE
Regression in Sedona 1.4.1 leading to OutOfMemoryException

### ISSUE THREAD

**Issue by umartin** [apache/sedona#1040] opened 2023-09-28 13:02 UTC
I recently upgraded our pipelines from Sedona 1.4.0 to Sedona 1.4.1 and one of them is failing with OutOfMemoryException. It fails even if I double the memory budget. I have tracked the regression down to this commit which added metrics to the NestedLoopJudgement. https://github.com/apache/sedona/pull/851/files#diff-2eb9b76007b1dc6ede8341c8e0864b3b7a7d0e2d4e7203220ec1e74c590124f9

## Expected behavior

No drastic increase in memory use.

## Actual behavior

OOM

## Steps to reproduce the problem

Run a job with no index and a large number of partitions. Sedona 1.4.1 need significantly more memory.

## Settings

sedona.global.index=false
sedona.join.numpartition=20000

Sedona version = 1.4.1

Apache Spark version = 3.4

API type = Java and Python tested

Scala version = 2.12

JRE version = 17

Python version = 3.11

Environment = Standalone

**Comment by umartin** [comment] 2023-09-28 13:14
With a custom build of v 1.4.1 where the metrics are removed or replaced by a LongAccumulator there is no regression regarding memory use.

I think the custom metric class in Sedona is build on a misconception. Spark already tracks accumulators per task. There is no need for a map accumulator. The Sedona Metrics class seems to have a large memory overhead, especially when there are a large number of tasks.

Current metrics in Spark UI (leading to OOM for many tasks):
Accumulator summary:
![Screenshot from 2023-09-28 12-06-02](https://github.com/apache/sedona/assets/1275096/f3df7d6e-4865-4d5a-a1eb-0613a981a5a1)
Tasks details:
![image](https://github.com/apache/sedona/assets/1275096/c5f9b3f6-eb68-45b0-a15f-0da979c52e07)

With LongAccumulator (no memory overhead):
![image](https://github.com/apache/sedona/assets/1275096/fb525923-a36a-4d5a-a903-edc97cc12da1)
Task details:
![image](https://github.com/apache/sedona/assets/1275096/dcdbf13f-eda3-4ca7-be15-4dbe90f7f19b)

**Comment by RinatVeliakhmedov-TomTom** [comment] 2023-09-28 13:55
I'm facing a similar issue that seems at least related to this. On a very big distance join, the driver just crashes with an unknown reason. Since I'm using it in Databricks, it doesn't manage to save proper logs, so I can't say for sure, but these kinds of errors almost always means OOM.
Would be great to be able to disable the accumulators.

**Comment by jiayuasu** [comment] 2023-09-28 15:34
Thank you all for isolating the root cause. I will fix this today. Sedona 1.5.0 will be out in around 1 week and this will be included.

**Closed** 2023-09-29 07:50 UTC
